version: '3.8'

services:
  limo-node-server: 
    restart: always
    build: 
      context: "./node-server"
    environment:
      - BACKEND_URL

  limo-ros-server:
    restart: always
    build: 
      context: "./ros-server"
    depends_on:
      - limo-bridge-server
      - limo-node-server

  limo-bridge-server:
    restart: always
    build: 
      context: "./bridge-server"
    environment:
      - ROS_MASTER_URI=http://172.29.170.62:11311
    ports:
      - 11311:11311
