version: '3.8'

services:
  interface-client: 
    restart: always
    build: 
      context: ./client
    ports:
      - 4200:4200
    depends_on:
      - server-interface

  server-interface:
    restart: always
    build: 
      context: ./server
    ports:
      - 9330:9330
    environment:
      - LIMO_IP_1
      - LIMO_IP_2
