version: '3.3'

services:
  interface-client: 
    restart: always
    build: 
      context: ./client
    ports:
      - 4200:4200
    depends_on:
      - server-interface
    environment:
      - BACKEND_IP

  server-interface:
    restart: always
    build: 
      context: ./server
    ports:
      - 9330:9330
    environment:
      - IS_SIMULATION
