version: '3.8'

services:
  interface-client: 
    restart: always
    build: 
      context: ./client
    ports:
      - 4200:4200
    depends_on:
      - server-interface
    networks:
      - project-net
    links:
      - "server-interface:server"

  server-interface:
    restart: always
    build: 
      context: ./server
    ports:
      - 9330:9330
    networks:
      - project-net

networks:
    project-net:
        driver: bridge


